
<body>
    <h1>Bienvenido al Sistema de Administración del Hospital</h1>

    <!-- Botón para Iniciar Sesión -->
    <a href="/login">
        <button>Iniciar Sesión</button>
    </a>

    <!-- Botón para Crear Usuario -->
    <a href="/guardar-usuario">
        <button>Crear Usuario</button>
    </a>

    <!-- Otros contenidos que pueden ir en el index -->
    <p>Este es el sistema donde podrás gestionar citas y pacientes.</p>
</body>
</html>