<?php include '../templates/header.phtml'; ?>

<h2>Iniciar sesión</h2>
<form action="/login" method="POST">
    <label for="usuario">Usuario:</label>
    <input type="text" id="usuario" name="usuario" required><br>

    <label for="password">Contraseña:</label>
    <input type="password" id="password" name="password" required><br>

    <button type="submit">Ingresar</button>
</form>

<?php if (isset($error)): ?>
    <p style="color: red;"><?= $error ?></p>
    <a href="/crear-usuario">
        <button>Crear una cuenta nueva</button>
    </a>
<?php endif; ?>

<?php include '../templates/footer.phtml'; ?>