<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
echo "Ruta actual: " . __DIR__ . "<br>"; // Muestra la ruta del directorio actual
echo "Intentando incluir: " . realpath('../templates/header.phtml') . "<br>"; // Muestra la ruta absoluta del archivo
include '../templates/header.phtml'; // Intenta incluir el archivo
?>
<?php include $_SERVER['DOCUMENT_ROOT'] . '/asd/hospital/templates/header.phtml'; ?>


<h2>Crear una nueva cuenta</h2>
<form action="<?= BASE_URL ?>guardar-usuario" method="POST">
    <label for="nombre">Nombre:</label>
    <input type="text" id="nombre" name="nombre" required><br>

    <label for="apellido">Apellido:</label>
    <input type="text" id="apellido" name="apellido" required><br>

    <label for="usuario">Usuario:</label>
    <input type="text" id="usuario" name="usuario" required><br>

    <label for="password">Contraseña:</label>
    <input type="password" id="password" name="password" required><br>

    <button type="submit">Registrar</button>
</form>

<?php require 'templates/footer.phtml'; ?>