<?php include '../templates/header.phtml'; ?>

<h2>Crear una nueva cuenta</h2>
<form action="/guardar-usuario" method="POST">
    <label for="nombre">Nombre:</label>
    <input type="text" id="nombre" name="nombre" required><br>

    <label for="apellido">Apellido:</label>
    <input type="text" id="apellido" name="apellido" required><br>

    <label for="usuario">Usuario:</label>
    <input type="text" id="usuario" name="usuario" required><br>

    <label for="password">Contraseña:</label>
    <input type="password" id="password" name="password" required><br>

    <button type="submit">Registrar</button>
</form>

<?php include '../templates/footer.phtml'; ?>