<main class="container mx-auto mt-8">
    <h2 class="text-3xl font-bold mb-8 text-center text-gray-800">Solicitar Turno</h2>

    <div class="bg-white shadow-lg rounded-lg p-6">
        <form action="agregarCita" method="POST">
            <div class="mb-4">
                <label for="paciente" class="block text-gray-700 font-bold mb-2">Seleccione el Paciente:</label>
                <select name="paciente_id" id="paciente" required class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                    <?php
                    foreach($pacientes as $paciente ):
                    ?>
                    <option value=" <?php echo ($paciente ->id) ?>">
                        <?php echo ($paciente->nombre) ?>
                    </option>
                    <?php
                    endforeach;
                    ?>
                </select>
            </div>

            <div class="mb-4">
                <label for="fecha" class="block text-gray-700 font-bold mb-2">Fecha de la Cita:</label>
                <input type="date" name="fecha" id="fecha" required class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>

            <div class="mb-4">
                <label for="hora" class="block text-gray-700 font-bold mb-2">Hora de la Cita:</label>
                <input type="time" name="hora" id="hora" required class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>

            <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded-full transition">Solicitar Turno</button>
        </form>
    </div>
</main>
