<?php require 'templates/header.phtml';
require 'agregarCita.phtml'; ?>

<main class="container mx-auto mt-8">
    <h2 class="text-3xl font-bold mb-8 text-center text-gray-800">Listado de Citas</h2>
    
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <?php foreach ($citas as $cita): ?>
            <div class="bg-white shadow-lg rounded-lg overflow-hidden transition transform hover:-translate-y-1 hover:shadow-xl">
                <div class="bg-blue-500 text-white p-4">
                    <h3 class="text-2xl font-bold mb-1">
                        <?php echo htmlspecialchars($cita->paciente_id); ?>
                    </h3>
                </div>
                <div class="p-6">
                    <p class="text-gray-700 mb-4">
                        <span class="font-bold">Fecha:</span> <?php echo htmlspecialchars($cita->fecha); ?>
                    </p>
                    <p class="text-gray-700 mb-4">
                        <span class="font-bold">Hora:</span> <?php echo htmlspecialchars($cita->hora); ?>
                    </p>
                    
                    <p class="text-gray-700 mb-4">
                        <span class="font-bold">Paciente ID: <?= htmlspecialchars($cita->paciente_id) ?>
                    </p>
                    <div class="flex justify-between items-center">
                        <a href="citas/<?php echo $cita->id; ?>" 
                        class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded-full transition">
                        Ver detalles
                    </a>
                    <div class="flex space-x-2">
                            <a href="editarCita/<?= $cita->id ?>" 
                            class="bg-yellow-500 hover:bg-yellow-600 text-white py-2 px-4 rounded-full transition">
                            Editar
                        </a>
                        <form action="eliminarCita/<?php echo $cita->id; ?>" method="POST" onsubmit="return confirm('¿Estás seguro de que deseas eliminar a esta cita?');">
                            <button type="submit" class="bg-red-500 hover:bg-red-600 text-white py-2 px-4 rounded-full transition">
                                Eliminar
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</main>

<?php require 'templates/footer.phtml'; ?>