
<?php require 'header.phtml'?>
<?php require 'formuAgregarPaciente.phtml'?>
<main class="container mx-auto mt-8">
    <h2 class="text-3xl font-bold mb-8 text-center text-gray-800">Listado de Pacientes</h2>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <?php foreach ($pacientes as $paciente): ?>
            <div class="bg-white shadow-lg rounded-lg overflow-hidden transition transform hover:-translate-y-1 hover:shadow-xl">
                <div class="bg-blue-500 text-white p-4">
                    <h3 class="text-2xl font-bold mb-1">
                        <?php echo htmlspecialchars($paciente->nombre); ?>
                    </h3>
                </div>
                <div class="p-6">
                    <p class="text-gray-700 mb-4">
                        <span class="font-bold">Apellido:</span> <?php echo htmlspecialchars($paciente->apellido); ?>
                    </p>
                    
                    <!-- Mostrar la foto del paciente -->
                    <?php if (!empty($paciente->foto)): ?>
                        <div class="mb-4">
                            <img src="<?= htmlspecialchars($paciente->foto); ?>" alt="Foto de <?= htmlspecialchars($paciente->nombre); ?>" class="w-32 h-32 object-cover rounded-full">
                        </div>
                    <?php else: ?>
                        <p>No se proporcionó una foto.</p>
                    <?php endif; ?>

                    <div class="flex justify-between items-center">
                        <a href="pacientePorId/<?php echo $paciente->id; ?>" 
                           class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded-full transition">
                            Ver detalles
                        </a>
                        <div class="flex space-x-2">
                            <a href="editarPaciente/<?= $paciente->id ?>" 
                               class="bg-yellow-500 hover:bg-yellow-600 text-white py-2 px-4 rounded-full transition">
                                Editar
                            </a>
                            <form action="eliminarPaciente/<?php echo $paciente->id; ?>" method="POST" onsubmit="return confirm('¿Estás seguro de que deseas eliminar a este paciente?');">
                                <button type="submit" class="bg-red-500 hover:bg-red-600 text-white py-2 px-4 rounded-full transition">
                                    Eliminar
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</main>
