<?php include '../hospital/templates/header.phtml'; ?>

<h1>Agregar Paciente</h1>
<form method="post">
    <label>Nombre:</label>
    <input type="text" name="nombre">
    
    <label>Apellido:</label>
    <input type="text" name="apellido">
    
    <label>Usuario:</label>
    <input type="text" name="usuario">
    
    <label>Contraseña:</label>
    <input type="password" name="contrasena">
    
    <button type="submit">Agregar</button>
</form>

<?php include '../hospital/templates/footer.phtml'; ?>